### ISSUE TITLE
Sporadic failure of dependency_resolution_test.go

### ISSUE THREAD

**Issue by kczulko** [tweag/gazelle_cabal#19]
**Describe the bug**
```
INFO: From Testing //gazelle_cabal:gazelle_cabal_test:
==================== Test output for //gazelle_cabal:gazelle_cabal_test:
--- FAIL: TestToolsToComponents (0.00s)
    dependency_resolution_test.go:218: got map[hsinspect:[lib exe:hsinspect] tasty-discover:[lib exe:tasty exe:tasty-discover]], wanted map[hsinspect:[lib exe:hsinspect] tasty-discover:[lib exe:tasty-discover exe:tasty]]
FAIL
```

https://github.com/tweag/gazelle_cabal/runs/5146544871?check_suite_focus=true

Maybe reflect.DeepEquals will help - to be checked.

**Comment by facundominguez** [comment]
How about:
https://github.com/tweag/gazelle_cabal/pull/18/commits/dd05df18d55d117a21d4ec76bd14a499cdbb4729
?
I think we want the tested function to be more deterministic.
