### ISSUE TITLE
More precise type for RuleInfo regarding attrs

### ISSUE THREAD

**Issue by googleson78** [tweag/gazelle_cabal#30]
Currently, `attrs` in `RuleInfo` is a list of text-keyed tuples. In [reality](https://github.com/tweag/gazelle_cabal/blob/4d3cba80588c054bd97ec8fe2a88fd75fa6f8c21/cabalscan/src/CabalScan/RuleGenerator.hs#L189), this is always a list containing at most 4 things, with known keys. I think it would be an improvement to instead split `attrs` out to these 4 things.

Pros:
* more accurately models reality (?)
* it makes the code clearer
  * you have to scour less to find out what `attrs` could be
  * more descriptive names
  * easier testing (can directly access the field you want to check)
  * immediately obvious we don't handle all possible attributes
  
Cons:
* more code
* more code to add a new attribute

**Comment by facundominguez** [comment]
This proposal looks good to me. Thanks for creating the issue.

**Comment by googleson78** [comment]
Working on this
