### ISSUE TITLE
Upgrade rules_go version to v0.33 (?)

### ISSUE THREAD

**Issue by kczulko** [tweag/gazelle_cabal#37]
**Describe the bug**
It's not a bug :) Adding to the backlog :)

I've got just notified about this: https://github.com/bazelbuild/bazel-gazelle/issues/1217#issuecomment-1148571276

If that's true we can upgrade rules_go version and remove [this](https://github.com/tweag/gazelle_cabal/blob/34a41345973cdffa29bf4d5d349439e86fc30ed3/WORKSPACE#L118) workaround.

**Comment by facundominguez** [comment]
Thanks @kczulko! I don't understand what the workaround to remove is, though.

**Comment by whs-dot-hk** [comment]
I don't think v33 works without the workaround

**Comment by whs-dot-hk** [comment]
You can reproduce the error with this repo https://github.com/whs-dot-hk/gazelle-test

**Comment by kczulko** [comment]
> I don't think v33 works without the workaround

I confirm, this doesn't work. Just updated rules_go and removed `org_golang_x_xerrors` from the WORKSPACE and compilation fails.

I am closing this issue. Thx.
